# Generated by Django 2.2.7 on 2019-11-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.CharField(max_length=200)),
                ('user_password', models.CharField(max_length=200)),
                ('user_phone', models.IntegerField()),
                ('user_photo', models.ImageField(blank=True, upload_to='book/seller_photos/%Y/%m/%d/')),
                ('user_country', models.CharField(max_length=100)),
                ('user_state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
