# Generated by Django 2.2.7 on 2019-11-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookseller',
            name='user_phone',
            field=models.CharField(max_length=100),
        ),
    ]
