# Generated by Django 2.2.7 on 2019-11-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191120_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookseller',
            name='city',
        ),
        migrations.RemoveField(
            model_name='bookseller',
            name='user_country',
        ),
        migrations.AddField(
            model_name='bookseller',
            name='user_address',
            field=models.CharField(default='xyz', max_length=300),
        ),
        migrations.AddField(
            model_name='bookseller',
            name='user_city',
            field=models.CharField(default='xyz', max_length=100),
        ),
    ]
