# Generated by Django 2.2.7 on 2019-11-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200)),
                ('book_price', models.IntegerField()),
                ('book_edition', models.CharField(max_length=200)),
                ('book_author', models.CharField(max_length=200)),
                ('book_old', models.IntegerField()),
                ('book_page', models.IntegerField()),
                ('book_description', models.TextField(max_length=200)),
                ('book_image_1', models.ImageField(blank=True, upload_to='book/book_photos/%Y/%m/%d')),
                ('book_image_2', models.ImageField(blank=True, upload_to='book/book_photos/%Y/%m/%d')),
                ('book_image_3', models.ImageField(blank=True, upload_to='book/book_photos/%Y/%m/%d')),
                ('book_image_4', models.ImageField(blank=True, upload_to='book/book_photos/%Y/%m/%d')),
            ],
        ),
    ]
