# Generated by Django 2.2.7 on 2019-11-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_category',
            field=models.CharField(default='abc', max_length=200),
        ),
    ]
